FROM python:3.8.2

COPY dev-requirements.txt /tmp/dev-requirements.txt
RUN pip install -r /tmp/dev-requirements.txt

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
